kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: online-admins-rolebinding
  namespace: 
subjects:
- kind: User
  name: dan
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

