kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developers-binding
  namespace: default
subjects:
- kind: User
  name: bob
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io

